### ISSUE TITLE
Discover and list PlusPlus functionality

### ISSUE THREAD

**Issue by eruizdechavez** [phpmx/phpmxbot#13]
In order to get the points handler in the bot to a good state, I would like to have a list of all existing functionality on the existing PlusPlus bot so that we can decide if we want all of it, or if we want to deprecate certain pieces.

So far some bits and pieces have surfaced over discussions in Slack, but I do not have a comprehensive list.

As far as I know these are missing on the new points handler:

- Self ++ and --
- ~~Special case: ++--~~
- Responses by PlusPlus when adding or removing points
- ~Ignore inline code and code blocks (this could get a bit tricky)~

Am I missing others?

**Comment by dmouse** [comment]
Existing messages 

```
'¡Felicidades!',
    '¡Lo tienes!',
    'Bravo.',
    'Bien hecho.',
    '¡Gran trabajo!',
    'Exquisito.',
    'Encantador.',
    'Soberbio.',
    '¡Clásico!',
    'Notorio.',
    '¡Bien, bien!',
    'Bien jugado.',
    'Mis más sinceras felicitaciones.',
    'Delicioso.',
    ':nice:',
    ':nyan:',
    ':party'
```

**Comment by dmouse** [comment]
-- messages

```
'¿De verdad?',
    'Oh :slightly_frowning_face:.',
    'Ya veo.',
    'Ouch.',
    'Eso duele.',
    'Oh.',
    'Que mal.',
    'Mis condolencias.',
    'Suerte para la próxima',
    ':trollface:',
    ':sadpanda:'
```

**Comment by dmouse** [comment]
self messages
```
    'Hahahahahahaha no.',
    'Nope.',
    'No. Simplemente no.',
    ':facepalm:',
    ':wat:'
```

**Comment by eruizdechavez** [comment]
Documented as #25.
