### ISSUE TITLE
Welcome private message

### ISSUE THREAD

**Issue by dmouse** [phpmx/phpmxbot#16]
Send a private welcome message to new users in Slack

**Comment by eruizdechavez** [comment]
Main functionality to enable this feature is described in #14.

**Comment by eruizdechavez** [comment]
@dmouse once #28 is merged this will be resolved by adding the proper message in the data base.

**Comment by eruizdechavez** [comment]
This feature is already provided by Slack on the on boarding process ([Getting Started Page](https://phpmx.slack.com/customize/get-started)). We also confirmed it is working for the most recent members.
