### ISSUE TITLE
Add a web leaderboard

### ISSUE THREAD

**Issue by eruizdechavez** [phpmx/phpmxbot#29]
Similar to what we have with plusplus today, we should have a web version of the leaderboard where we can see points, and maybe some other stats (monthly, yearly, all time).

**Comment by gueroverde** [comment]
Where would the page live, on this site with the bot, or would this project just provide an API that would consume the phpmx website?

**Comment by eruizdechavez** [comment]
I haven't planned anything on this issue yet. I am just adding it here so we can start bouncing ideas after v1.0.0 is released.

**Comment by eruizdechavez** [comment]
Update: Since we are also starting to work on the website redesign, this leaderboard will most likely be part of the main site, hence instead of a dashboard, we now need this to be an API.

As for the authentication, we can keep things simpler and use a static token in the header. No need to go crazy with OAuth or JWT for now.

**Comment by RZEROSTERN** [comment]
Is there any update on this issue?
Maybe I can check it out at least the API, although it doesn't count for Hacktoberfest 😃

**Comment by eruizdechavez** [comment]
@RZEROSTERN I believe we do not have any pull requests about it... yet. There is some interest, so you could either create your own version, or team up with whom ever has expressed interest in the comments 👍 .

**Comment by gueroverde** [comment]
Go ahead @RZEROSTERN  I remember @sirpyerre already start working on it, maybe we can coordinate a meet to develop on a group if you guys want

**Comment by Sirpyerre** [comment]
I tried but I dont understand where add the new code :'(

**Comment by RZEROSTERN** [comment]
I've seen many features to improve in the development part, but I don't want to harm production.
@eruizdechavez I've put some doubts on Slack. I want to contribute with this project.

**Comment by gueroverde** [comment]
I already started working on it, i have a branch https://github.com/gueroverde/phpmxbot/tree/api at this moment i only created a kernel to manage the api call , the logic on the controller is still missing, so let me know if you have any comment or if you want to contribute to it on any way please let me know 😄
